apiVersion: v1
kind: Pod
metadata:
  name: segundopod
  labels:
    app: segundopod
spec:
  containers:
    - name: segundopod
      image: mysql:8.0
      ports:
        - containerPort: 3306
      env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: q1w2e3r4
        - name: "MYSQL_DATABASE"
          value: empresa
        - name: "MYSQL_PASSWORD"
          value: q1w2e3r4
